export type Capability = "High" | "Medium" | "Low";

export type MedicalNeed =
  | "Emergency Surgery"
  | "ICU + Oxygen"
  | "Dialysis"
  | "Neonatal Care"
  | "Trauma Care";

export interface Facility {
  id: string;
  name: string;
  state: string;
  city: string;
  pinCode: string;
  latitude: number;
  longitude: number;
  emergencySurgeryCapability: Capability;
  icuCapability: Capability;
  dialysisCapability: Capability;
  neonatalCapability: Capability;
  traumaCapability: Capability;
  trustScore: number;
  riskWarning: string;
  recommendationReason: string;
  hasOxygen: boolean;
  hasSurgeon: boolean;
  hasAnesthesiologist: boolean;
  hasICU: boolean;
  hasDialysis: boolean;
  hasAmbulance: boolean;
}

export const MEDICAL_NEEDS: MedicalNeed[] = [
  "Emergency Surgery",
  "ICU + Oxygen",
  "Dialysis",
  "Neonatal Care",
  "Trauma Care",
];

export const INDIAN_STATES = [
  "Bihar",
  "Karnataka",
  "Maharashtra",
  "Uttar Pradesh",
];

const NEED_TO_FIELD: Record<MedicalNeed, keyof Facility> = {
  "Emergency Surgery": "emergencySurgeryCapability",
  "ICU + Oxygen": "icuCapability",
  Dialysis: "dialysisCapability",
  "Neonatal Care": "neonatalCapability",
  "Trauma Care": "traumaCapability",
};

export function facilityMatchesNeed(f: Facility, need: MedicalNeed): boolean {
  const cap = f[NEED_TO_FIELD[need]] as Capability;
  return cap === "High" || cap === "Medium";
}

export const FACILITIES: Facility[] = [
  {
    id: "f1",
    name: "Patna Medical College Hospital",
    state: "Bihar",
    city: "Patna",
    pinCode: "800004",
    latitude: 25.6127,
    longitude: 85.1376,
    emergencySurgeryCapability: "High",
    icuCapability: "High",
    dialysisCapability: "Medium",
    neonatalCapability: "Medium",
    traumaCapability: "High",
    trustScore: 84,
    riskWarning: "Frequent overcrowding; ER wait can exceed 40 minutes.",
    recommendationReason:
      "Largest government tertiary hospital in Bihar with verified trauma and surgical capacity.",
    hasOxygen: true,
    hasSurgeon: true,
    hasAnesthesiologist: true,
    hasICU: true,
    hasDialysis: true,
    hasAmbulance: true,
  },
  {
    id: "f2",
    name: "AIIMS Patna",
    state: "Bihar",
    city: "Patna",
    pinCode: "801507",
    latitude: 25.5519,
    longitude: 85.0931,
    emergencySurgeryCapability: "High",
    icuCapability: "High",
    dialysisCapability: "High",
    neonatalCapability: "High",
    traumaCapability: "High",
    trustScore: 92,
    riskWarning: "Advance appointment recommended for non-emergency cases.",
    recommendationReason:
      "Premier institute with full-spectrum critical care and neonatal ICU.",
    hasOxygen: true,
    hasSurgeon: true,
    hasAnesthesiologist: true,
    hasICU: true,
    hasDialysis: true,
    hasAmbulance: true,
  },
  {
    id: "f3",
    name: "Sadar Hospital Gaya",
    state: "Bihar",
    city: "Gaya",
    pinCode: "823001",
    latitude: 24.7914,
    longitude: 85.0002,
    emergencySurgeryCapability: "Medium",
    icuCapability: "Low",
    dialysisCapability: "Low",
    neonatalCapability: "Medium",
    traumaCapability: "Medium",
    trustScore: 62,
    riskWarning: "Limited ICU beds and intermittent oxygen supply.",
    recommendationReason:
      "Closest district hospital for stabilization before tertiary referral.",
    hasOxygen: true,
    hasSurgeon: true,
    hasAnesthesiologist: false,
    hasICU: false,
    hasDialysis: false,
    hasAmbulance: true,
  },
  {
    id: "f4",
    name: "Ruby Hall Clinic",
    state: "Maharashtra",
    city: "Pune",
    pinCode: "411001",
    latitude: 18.5362,
    longitude: 73.8826,
    emergencySurgeryCapability: "High",
    icuCapability: "High",
    dialysisCapability: "High",
    neonatalCapability: "High",
    traumaCapability: "High",
    trustScore: 89,
    riskWarning: "ICU occupancy frequently above 90%.",
    recommendationReason:
      "NABH accredited multi-specialty with rapid surgical response team.",
    hasOxygen: true,
    hasSurgeon: true,
    hasAnesthesiologist: true,
    hasICU: true,
    hasDialysis: true,
    hasAmbulance: true,
  },
  {
    id: "f5",
    name: "KEM Hospital Mumbai",
    state: "Maharashtra",
    city: "Mumbai",
    pinCode: "400012",
    latitude: 19.0034,
    longitude: 72.8421,
    emergencySurgeryCapability: "High",
    icuCapability: "Medium",
    dialysisCapability: "High",
    neonatalCapability: "High",
    traumaCapability: "High",
    trustScore: 81,
    riskWarning: "Equipment uptime ~82%; confirm dialysis slot in advance.",
    recommendationReason:
      "Public tertiary center with experienced trauma and nephrology teams.",
    hasOxygen: true,
    hasSurgeon: true,
    hasAnesthesiologist: true,
    hasICU: true,
    hasDialysis: true,
    hasAmbulance: true,
  },
  {
    id: "f6",
    name: "Lilavati Hospital",
    state: "Maharashtra",
    city: "Mumbai",
    pinCode: "400050",
    latitude: 19.0509,
    longitude: 72.8294,
    emergencySurgeryCapability: "High",
    icuCapability: "High",
    dialysisCapability: "Medium",
    neonatalCapability: "High",
    traumaCapability: "Medium",
    trustScore: 87,
    riskWarning: "Premium pricing; verify insurance coverage beforehand.",
    recommendationReason:
      "Strong neonatal outcomes and 24/7 surgical theatre availability.",
    hasOxygen: true,
    hasSurgeon: true,
    hasAnesthesiologist: true,
    hasICU: true,
    hasDialysis: true,
    hasAmbulance: true,
  },
  {
    id: "f7",
    name: "Sassoon General Hospital",
    state: "Maharashtra",
    city: "Pune",
    pinCode: "411001",
    latitude: 18.5304,
    longitude: 73.8736,
    emergencySurgeryCapability: "Medium",
    icuCapability: "Medium",
    dialysisCapability: "Low",
    neonatalCapability: "Medium",
    traumaCapability: "High",
    trustScore: 71,
    riskWarning: "High patient load; expect longer admission times.",
    recommendationReason:
      "Government trauma center with reliable emergency surgical access.",
    hasOxygen: true,
    hasSurgeon: true,
    hasAnesthesiologist: true,
    hasICU: true,
    hasDialysis: false,
    hasAmbulance: true,
  },
  {
    id: "f8",
    name: "Manipal Hospital Whitefield",
    state: "Karnataka",
    city: "Bengaluru",
    pinCode: "560066",
    latitude: 12.9698,
    longitude: 77.7499,
    emergencySurgeryCapability: "High",
    icuCapability: "High",
    dialysisCapability: "High",
    neonatalCapability: "High",
    traumaCapability: "Medium",
    trustScore: 88,
    riskWarning: "No active warnings reported in the last 90 days.",
    recommendationReason:
      "Strong neonatal ICU outcomes and dedicated dialysis unit.",
    hasOxygen: true,
    hasSurgeon: true,
    hasAnesthesiologist: true,
    hasICU: true,
    hasDialysis: true,
    hasAmbulance: true,
  },
  {
    id: "f9",
    name: "Victoria Hospital",
    state: "Karnataka",
    city: "Bengaluru",
    pinCode: "560002",
    latitude: 12.9606,
    longitude: 77.5747,
    emergencySurgeryCapability: "High",
    icuCapability: "Medium",
    dialysisCapability: "Medium",
    neonatalCapability: "Low",
    traumaCapability: "High",
    trustScore: 75,
    riskWarning: "Crowded outpatient department; emergency triage prioritized.",
    recommendationReason:
      "Major government trauma hospital with experienced surgical staff.",
    hasOxygen: true,
    hasSurgeon: true,
    hasAnesthesiologist: true,
    hasICU: true,
    hasDialysis: true,
    hasAmbulance: true,
  },
  {
    id: "f10",
    name: "KMC Hospital Mangalore",
    state: "Karnataka",
    city: "Mangalore",
    pinCode: "575001",
    latitude: 12.8703,
    longitude: 74.8425,
    emergencySurgeryCapability: "High",
    icuCapability: "High",
    dialysisCapability: "High",
    neonatalCapability: "Medium",
    traumaCapability: "Medium",
    trustScore: 83,
    riskWarning: "Limited helipad access; ground transport recommended.",
    recommendationReason:
      "Tertiary teaching hospital with verified ICU and dialysis capacity.",
    hasOxygen: true,
    hasSurgeon: true,
    hasAnesthesiologist: true,
    hasICU: true,
    hasDialysis: true,
    hasAmbulance: true,
  },
  {
    id: "f11",
    name: "SGPGI Lucknow",
    state: "Uttar Pradesh",
    city: "Lucknow",
    pinCode: "226014",
    latitude: 26.7544,
    longitude: 80.9458,
    emergencySurgeryCapability: "High",
    icuCapability: "High",
    dialysisCapability: "High",
    neonatalCapability: "High",
    traumaCapability: "Medium",
    trustScore: 90,
    riskWarning: "Referral-based admissions for non-emergency cases.",
    recommendationReason:
      "Premier postgraduate institute with comprehensive critical care.",
    hasOxygen: true,
    hasSurgeon: true,
    hasAnesthesiologist: true,
    hasICU: true,
    hasDialysis: true,
    hasAmbulance: true,
  },
  {
    id: "f12",
    name: "BHU Trauma Centre",
    state: "Uttar Pradesh",
    city: "Varanasi",
    pinCode: "221005",
    latitude: 25.2677,
    longitude: 82.9913,
    emergencySurgeryCapability: "High",
    icuCapability: "Medium",
    dialysisCapability: "Medium",
    neonatalCapability: "Medium",
    traumaCapability: "High",
    trustScore: 78,
    riskWarning: "ICU bed availability fluctuates; call ahead.",
    recommendationReason:
      "Dedicated trauma facility with 24/7 surgical and anesthesia coverage.",
    hasOxygen: true,
    hasSurgeon: true,
    hasAnesthesiologist: true,
    hasICU: true,
    hasDialysis: true,
    hasAmbulance: true,
  },
  {
    id: "f13",
    name: "District Hospital Agra",
    state: "Uttar Pradesh",
    city: "Agra",
    pinCode: "282002",
    latitude: 27.1767,
    longitude: 78.0081,
    emergencySurgeryCapability: "Medium",
    icuCapability: "Low",
    dialysisCapability: "Low",
    neonatalCapability: "Medium",
    traumaCapability: "Medium",
    trustScore: 60,
    riskWarning: "Limited ICU and no on-site dialysis unit.",
    recommendationReason:
      "Useful for stabilization and basic emergency surgical care before transfer.",
    hasOxygen: true,
    hasSurgeon: true,
    hasAnesthesiologist: false,
    hasICU: false,
    hasDialysis: false,
    hasAmbulance: true,
  },
  {
    id: "f14",
    name: "KGMU Lucknow",
    state: "Uttar Pradesh",
    city: "Lucknow",
    pinCode: "226003",
    latitude: 26.8721,
    longitude: 80.9126,
    emergencySurgeryCapability: "High",
    icuCapability: "High",
    dialysisCapability: "High",
    neonatalCapability: "High",
    traumaCapability: "High",
    trustScore: 86,
    riskWarning: "High footfall; expect queues at registration.",
    recommendationReason:
      "Comprehensive government medical university with strong trauma and neonatal units.",
    hasOxygen: true,
    hasSurgeon: true,
    hasAnesthesiologist: true,
    hasICU: true,
    hasDialysis: true,
    hasAmbulance: true,
  },
];
