/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSearchFacilitiesRouteImport } from './routes/api/search-facilities'
import { Route as ApiMedicalDesertsRouteImport } from './routes/api/medical-deserts'
import { Route as ApiLocationOptionsRouteImport } from './routes/api/location-options'
import { Route as ApiDatabricksHealthRouteImport } from './routes/api/databricks-health'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchFacilitiesRoute = ApiSearchFacilitiesRouteImport.update({
  id: '/api/search-facilities',
  path: '/api/search-facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMedicalDesertsRoute = ApiMedicalDesertsRouteImport.update({
  id: '/api/medical-deserts',
  path: '/api/medical-deserts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocationOptionsRoute = ApiLocationOptionsRouteImport.update({
  id: '/api/location-options',
  path: '/api/location-options',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDatabricksHealthRoute = ApiDatabricksHealthRouteImport.update({
  id: '/api/databricks-health',
  path: '/api/databricks-health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/databricks-health': typeof ApiDatabricksHealthRoute
  '/api/location-options': typeof ApiLocationOptionsRoute
  '/api/medical-deserts': typeof ApiMedicalDesertsRoute
  '/api/search-facilities': typeof ApiSearchFacilitiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/databricks-health': typeof ApiDatabricksHealthRoute
  '/api/location-options': typeof ApiLocationOptionsRoute
  '/api/medical-deserts': typeof ApiMedicalDesertsRoute
  '/api/search-facilities': typeof ApiSearchFacilitiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/databricks-health': typeof ApiDatabricksHealthRoute
  '/api/location-options': typeof ApiLocationOptionsRoute
  '/api/medical-deserts': typeof ApiMedicalDesertsRoute
  '/api/search-facilities': typeof ApiSearchFacilitiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/databricks-health'
    | '/api/location-options'
    | '/api/medical-deserts'
    | '/api/search-facilities'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/databricks-health'
    | '/api/location-options'
    | '/api/medical-deserts'
    | '/api/search-facilities'
  id:
    | '__root__'
    | '/'
    | '/api/databricks-health'
    | '/api/location-options'
    | '/api/medical-deserts'
    | '/api/search-facilities'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDatabricksHealthRoute: typeof ApiDatabricksHealthRoute
  ApiLocationOptionsRoute: typeof ApiLocationOptionsRoute
  ApiMedicalDesertsRoute: typeof ApiMedicalDesertsRoute
  ApiSearchFacilitiesRoute: typeof ApiSearchFacilitiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search-facilities': {
      id: '/api/search-facilities'
      path: '/api/search-facilities'
      fullPath: '/api/search-facilities'
      preLoaderRoute: typeof ApiSearchFacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/medical-deserts': {
      id: '/api/medical-deserts'
      path: '/api/medical-deserts'
      fullPath: '/api/medical-deserts'
      preLoaderRoute: typeof ApiMedicalDesertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/location-options': {
      id: '/api/location-options'
      path: '/api/location-options'
      fullPath: '/api/location-options'
      preLoaderRoute: typeof ApiLocationOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/databricks-health': {
      id: '/api/databricks-health'
      path: '/api/databricks-health'
      fullPath: '/api/databricks-health'
      preLoaderRoute: typeof ApiDatabricksHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDatabricksHealthRoute: ApiDatabricksHealthRoute,
  ApiLocationOptionsRoute: ApiLocationOptionsRoute,
  ApiMedicalDesertsRoute: ApiMedicalDesertsRoute,
  ApiSearchFacilitiesRoute: ApiSearchFacilitiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
